name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PROJECT: ADD_PROJECT_HERE
  BUCKET: ADD_BUCKET_HERE

jobs:
  test_direct_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master # Set up ADC for credentials
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        env:
            PROJECT: ${{ secrets.BUCKET }}
            BUCKET: ${{ secrets.PROJECT }}
            SERVICE_ACCOUNT: ${{ secrets.GCP_SA_KEY }}
        run: pytest --log-cli-level=INFO tests/pubsub_it_test.py --test-pipeline-options="--runner=TestDataflowRunner \
            --project=$PROJECT --region=europe-west1 \
            --staging_location=gs://$BUCKET/staging \
            --temp_location=gs://$BUCKET/temp \
            --job_name=it-test-pipeline \
            --setup_file ./setup.py"
