name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PROJECT: ADD_PROJECT_HERE
  BUCKET: ADD_BUCKET_HERE

jobs:
  test_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest --cov=porter tests
  test_direct_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          apt-get install gcc python3-dev python3-setuptools
          pip uninstall crcmod
          pip install --no-cache-dir -U crcmod
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest --log-cli-level=INFO tests/pubsub_it_test.py --test-pipeline-options="--runner=TestDataflowRunner \
            --project={{ env.PROJECT }} --region=europe-west1 \
            --staging_location=gs://{{ env.BUCKET }}/staging \
            --temp_location=gs://{{ env.BUCKET }}/temp \
            --job_name=it-test-pipeline \
            --setup_file ./setup.py"
