name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
    BUCKET: word_count_example_test
    PROJECT: ${{ secrets.GCP_PROJECT }}

jobs:
  test_direct_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
      - uses: astral-sh/setup-uv@v10
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked
      - name: Run integration test with TestDirectRunner
        run: >
          uv run pytest -m it --log-cli-level=INFO tests/pubsub_it_test.py
          --test-pipeline-options="--runner=TestDirectRunner
          --project=${{ secrets.GCP_PROJECT }} --region=europe-west1
          --staging_location=gs://${{ env.BUCKET }}/staging
          --temp_location=gs://${{ env.BUCKET }}/temp
          --job_name=it-test-pipeline --setup_file ./pyproject.toml"
  test_dataflow_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
      - uses: astral-sh/setup-uv@v10
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked
      - name: Run integration test with TestDataflowRunner
        run: bash scripts/run_integration_test.sh
